

%%%%facts
%
%
%
%Facts taken from tech tree
%

coursename(sssbb,stochastic_simulations_in_systems_biology_and_biophysics).
coursename(cbb,cell_biology_and_bio-chemistry).
coursename(fomb,foundations_of_modern_biology).
coursename(acb,algorithms_in_computational_biology).
coursename(chi,chemoinformatics).
coursename(bip,biomedical_image_processing).
coursename(imb,introduction_to_mathematical_biology).
coursename(nb,network_biology).
coursename(ssb,systems_and_synthetic_biology).
coursename(icn,introduction_to_computational_neuroscience).
coursename(dsg,data_sciences_for_genomics).
coursename(mlba,machine_learning_for_biomedical_applications).
coursename(bdmh,big_data_mining_in_healthcare).
coursename(cgas,computational_gastronomy).
coursename(biostats,biostatistics).
coursename(cm,computing_for_medicine).
coursename(cadd,computer_aided_drug_design).
coursename(com,communication_skills).
coursename(tcom,technical_communication).
coursename(mad,modern_algorithm_design).
coursename(aa,advanced_algorithms).
coursename(toc,theory_of_computation).
coursename(cg,computer_graphics).
coursename(dip,digital_image_processing).
coursename(sml,statistical_machine_learning).
coursename(ml,machine_learning).
coursename(cv,computer_vision).
coursename(fcs,foundations_of_computer_security).
coursename(nsc,network_security).
coursename(nss-ii,networks_and_system_security_ii).
coursename(cmpt,complexity_theory).
coursename(biom,advanced_biometrics).
coursename(dhcs,designing_human_centered_systems).
coursename(fpp,foundations_of_parallel_programming).
coursename(pa,program_analysis).
coursename(dp,decision_procedures).
coursename(dmg,data_mining).
coursename(dbsi,database_system_implementation).
coursename(ir,information_retrieval).
coursename(ca,computer_architecture).
coursename(bml,bayesian_machine_learning).
coursename(tdl,theories_of_deep_learning).
coursename(ra,randomized_algorithms).
coursename(tmc,theory_of_modern_cryptography).
coursename(ga,introduction_to_graduate_algorithms).
coursename(ibc,introduction_to_blockchain_and_cryptocurrency).
coursename(aag,approximation_algorithms).
coursename(dscd,distributed_systems_concepts_design).
coursename(mas,multi-agent_systems).
coursename(mc,mobile_computing).
coursename(wn,wireless_networks).
coursename(ac,applied_cryptography).
coursename(se,security_engineering).
coursename(isc,introduction_to_spatial_computing).
coursename(nlp,natural_language_processing).
coursename(bda,big_data_analytics).
coursename(dsc,data_science).
coursename(mln,mining_large_networks).
coursename(gpu,gpu_computing).
coursename(pgm,probabilistic_graphical_models).
coursename(acv,advanced_computer_vision).
coursename(mca,multimedia_computing_and_applications).
coursename(rl,reinforcement_learning).
coursename(sdn,software_defined_networking).
coursename(mms,mobile_and_middleware_systems).
coursename(vr,virtual_reality).
coursename(imc,introduction_to_media_computing).
coursename(sap,speech_and_audio_processing).
coursename(ssiot,smart_sensing_for_internet_of_things_(iot)).
coursename(aiot,advanced_internet_of_things).
coursename(om,ontology_modeling).
coursename(sadre,systems_analysis_design_and_requirements_engineering).
coursename(spem,software_production_evolution_and_maintenance).
coursename(sdos,software_development_using_open_source).
coursename(pv,program_verification).
coursename(gp,geometry_processing).
coursename(oopd,object_oriented_programming_and_design).
coursename(kg,knowledge_graphs_in_practice).
coursename(dw,data_warehouse).
coursename(dlm,data_lifecycle_management).
coursename(scomp,statistical_computation).
coursename(iqc,introduction_to_quantum_computing).
coursename(aos,advanced_operating_systems).
coursename(sweb,semantic_web).
coursename(irob,robotics).
coursename(sr,social_robotics).
coursename(prmp,parallel_runtimes_for_modern_processors).
coursename(comn,communication_networks).
coursename(cf,collaborative_filtering).
coursename(dl,deep_learning).
coursename(aml,advanced_machine_learning).
coursename(ai,artificial_intelligence).
coursename(psosm,privacy_and_security_in_online_social_media).
coursename(tac,topics_in_adaptive_cybersecurity).
coursename(ns,network_science).
coursename(iia,information_integration_and_applications).
coursename(tais,trustworthy_ai_systems).
coursename(afc,affective_computing).
coursename(scv,special_topics_in_computer_vision).
coursename(eai,edge_ai).
coursename(mel,meta-learning).
coursename(ms,multimedia_security).
coursename(tse,topics_in_software_engineering_ai_in_se).
coursename(atmc,advanced_topics_in_mobile_computing).
coursename(nap,network_anonymity_and_privacy).
coursename(tc,topics_in_cryptanalysis).
coursename(ddv,design_drawing_visualization).
coursename(ihci,introduction_to_hci).
coursename(pis,prototyping_interactive_systems).
coursename(dpp,design_processes_and_perspectives).
coursename(vdc,visual_design_communication).
coursename(hci,human_computer_interaction).
coursename(iag,introduction_to_animation_and_graphics).
coursename(fmrp,film_making_and_radio_podcasting).
coursename(fae,fundamentals_of_audio_for_engineers).
coursename(i2d,introduction_to_2d_animation).
coursename(i3da,introduction_to_3d_character_animation).
coursename(nvc,narratives_in_visual_communication).
coursename(athcc,advanced_topics_in_human_centered_computing).
coursename(fve,fundamentals_of_video_for_engineers).
coursename(df,design_futures).
coursename(gdd,game_design_and_development).
coursename(wardi,wearable_applications_research_devices_interactions).
coursename(davp,digital_audio_video_production_workflow).
coursename(ispr,information_systems_in_public_health).
coursename(i3dd,introduction_to_3d_production_design_for_animation_and_games).
coursename(i3d,introduction_to_3d_animation).
coursename(img,introduction_to_motion_graphics).
coursename(dis,design_of_interactive_systems).
coursename(hcai,human_centred_ai).
coursename(iduda,inclusive_design_universal_design_accessibility).
coursename(atd,antennas_theory_and_design).
coursename(rs,radar_systems).
coursename(ssp,statistical_signal_processing).
coursename(prp,probability_and_random_process).
coursename(dhd,digital_hardware_design).
coursename(vdf,vlsi_design_flow).
coursename(scdt,system_on_chip_design_and_test).
coursename(ine,introduction_to_nanoelectronics).
coursename(iai,intelligent_applications_implementation_on_heterogeneous_platforms).
coursename(lvacd,low_voltage_analog_circuit_design).
coursename(icf,integrated_circuit_fabrication).
coursename(qmd,quantum_materials_and_devices).
coursename(snsf,satellite_navigation_and_sensor_fusion).
coursename(ocs,optical_communications_systems).
coursename(on,optical_networking).
coursename(wce,wireless_communication_evolution_from_3g_to_5g).
coursename(wsi,wireless_system_implementation).
coursename(pdcs,principals_of_digital_communication_system).
coursename(pho,photonics_fundamentals_applications).
coursename(owc,optical_and_wireless_convergence_for_beyond_5g_networks_and_iot).
coursename(cs,compressive_sensing).
coursename(sru,speech_recognition_and_understanding).
coursename(tla,transform_learning_and_applications).
coursename(gn,modeling_and_analysis_of_random_5g_networks).
coursename(dpm,data_processing_and_management).
coursename(lst,linear_systems_theory).
coursename(ocns,optimal_control_systems).
coursename(aeld,advanced_embedded_logic_design).
coursename(mlrc,machine_learning_techniques_for_real-time_control).
coursename(nlr,nonlinear_and_adaptive_control_of_robotic_systems).
coursename(ad,autonomous_driving).
coursename(mdt,memory_design_and_testing).
coursename(msd,mixed_signal_design).
coursename(sec,stochastic_estimation_and_control).
coursename(ma,macroeconomics).
coursename(eco,econometrics_i).
coursename(mb,money_and_banking).
coursename(me,microeconomics).
coursename(iea,introduction_to_economic_analysis).
coursename(gmt,game_theory).
coursename(io,industrial_organization).
coursename(md,market_design).
coursename(beco,behavioural_economics).
coursename(econ-2,econometrics_ii).
coursename(ssse,spatial_statistics_and_spatial_econometrics).
coursename(ff,foundations_of_finance).
coursename(vpm,valuation_and_portfolio_management).
coursename(drm,derivatives_and_risk_management).
coursename(mdp,markov_decision_processes).
coursename(dt,decision_theory).
coursename(rm,research_methods).
coursename(ecomm,entrepreneurial_communication).
coursename(ek,entrepreneurial_khichadi).
coursename(ef,entrepreneurial_finance).
coursename(rips,relevance_of_intellectual_property_for_startups).
coursename(nvp,new_venture_planning).
coursename(ciips,creativity_innovation_and_inventive_problem_solving).
coursename(hiee,healthcare_innovation_and_entrepreneurship_essentials).
coursename(evs,environmental_sciences).
coursename(eee,ecology_evolution_and_environment).
coursename(escm,effective_supply_chain_for_e_commerce).
coursename(eiitm,emerging_issues_in_it_management).
coursename(m-i,linear_algebra).
coursename(ps,probability_and_statistics).
coursename(m-iii,multivariate_calculus).
coursename(m-iv,differential_equations).
coursename(ds,discrete_structures).
coursename(nt,number_theory).
coursename(aa-i,abstract_algebra_i).
coursename(ra-i,real_analysis_i).
coursename(nm,numerical_methods).
coursename(iml,introduction_to_mathematical_logic).
coursename(alg,algebra).
coursename(gt,graph_theory).
coursename(cia,combinatorics_and_its_applications).
coursename(ra-ii,real_analysis-ii).
coursename(cmpa,complex_analysis).
coursename(ids,introduction_to_dynamical_systems).
coursename(spa,stochastic_processes_and_applications).
coursename(si,statistical_inference).
coursename(sc,scientific_computing).
coursename(lo,linear_optimization).
coursename(fm,fluid_mechainics).
coursename(ala,advanced_linear_algebra).
coursename(ant,algebraic_number_theory).
coursename(aa-ii,abstract_algebra_ii).
coursename(cot,coding_theory).
coursename(annt,analytic_number_theory).
coursename(cmo,combinatorial_optimization).
coursename(tnt,topics_in_number_theory).
coursename(mpt,measure_and_probability_theory).
coursename(ifa,introduction_to_functional_analysis).
coursename(crn,calculus_in_r^n).
coursename(fsem,finite_and_spectral_element_methods).
coursename(ipde,introduction_to_pde).
coursename(pst,point_set_toplogy).
coursename(pst-2,point_set_toplogy).
coursename(irg,introduction_to_riemannian_geometry_with_some_applications).
coursename(nsde,numerical_solutions_differential_equations).
coursename(ita,integral_transforms_and_their_applications).
coursename(cda,categorical_data_analysis).
coursename(coo,convex_optimization).
coursename(npde,numerical_partial_differential_equations).
coursename(vca,variational_calculus_and_their_applications).
coursename(psy,introduction_to_psychology).
coursename(ppsy,positive_psychology).
coursename(cp,cognitive_psychology).
coursename(sp,social_psychology).
coursename(atp,attention_and_perception).
coursename(lm,learning_and_memory).
coursename(ndm,neuroscience_of_decision_making).
coursename(cmm,cognition_of_motor_movement).
coursename(isa,introduction_to_sociology_and_anthropology).
coursename(cisp,contemporary_india_sociological_perspective).
coursename(snm,sociology_of_new_media).
coursename(asm,anthropology_and_social_media).
coursename(ba,business_anthropology).
coursename(its,information_technology_and_society).
coursename(oap,organizations_an_anthropological_perspective).
coursename(ccs,consumer_culture_and_society).
coursename(st1,sociological_theory).
coursename(sts,science_technology_and_society).
coursename(kces,key_concepts_in_economic_sociology).
coursename(ide,introduction_to_digital_ethnography).
coursename(us,urban_sociology).
coursename(dsr,digital_social_research).
coursename(gm,gender_and_media).
coursename(aerm,advance_ethnographic_research_methods).
coursename(ast,advanced_sociological_theory).
coursename(soi,sociology_of_india_themes_and_perspectives).
coursename(tfm,technology_and_the_future_of_work).
coursename(inst,intersectionality_studies).
coursename(ctrss,critical_thinking_and_readings_in_social_science).
coursename(iphi,introduction_to_philosophy).
coursename(ct,critical_thinking).
coursename(rmssd,research_methods_in_social_science_and_design).
coursename(ta,theatre_appreciation).
coursename(lit,introduction_to_the_study_of_literature).
coursename(nn,nation_and_her_narratives).
coursename(iim,introduction_to_indian_mythology).
coursename(ipa,indian_poetry_through_the_ages).
coursename(spp,social_and_political_philosophy).
coursename(tpee,theory_and_practice_of_engineering_ethics).
coursename(pok,perspectives_of_knowledge).
coursename(cies,computer_information_ethics_and_society).
coursename(dipp,democracy_in_india_principles_and_practices).
coursename(te,theories_of_ethics).
coursename(aw,advanced_writing).
coursename(ae,applied_ethics).
coursename(nmp,new_media_and_politics).
coursename(pom,philosophy_of_mind).
coursename(cpde,comparative_politics_in_digital_era).
coursename(uspp,urban_space_and_political_power).
coursename(pt,philosophy_of_technology).



coursecode(sssbb,bio506).
coursecode(cbb,bio511).
coursecode(fomb,bio512).
coursecode(acb,bio522).
coursecode(chi,bio523).
coursecode(bip,bio524).
coursecode(imb,bio531).
coursecode(nb,bio532).
coursecode(ssb,bio533).
coursecode(icn,bio534).
coursecode(dsg,bio541).
coursecode(mlba,bio542).
coursecode(bdmh,bio543).
coursecode(cgas,bio544).
coursecode(biostats,bio545).
coursecode(cm,cse585).
coursecode(cadd,bio561).
coursecode(com,com101).
coursecode(tcom,com301a).

coursecode(cmp,cse601).
coursecode(mad,cse519).
coursecode(aa,cse520).
coursecode(toc,cse322).
coursecode(cg,cse533).
coursecode(dip,cse540).
coursecode(sml,cse542).
coursecode(ml,cse543).
coursecode(cv,cse544).
coursecode(fcs,cse545).
coursecode(nsc,cse550).
coursecode(nss-ii,cse554).
coursecode(cmpt,cse621).
coursecode(biom,cse541).
coursecode(dhcs,cse501).
coursecode(fpp,cse502).
coursecode(pa,cse503).
coursecode(dp,cse504).
coursecode(dmg,cse506).
coursecode(dbsi,cse507).
coursecode(ir,cse508).
coursecode(ca,cse511).
coursecode(bml,cse515).
coursecode(tdl,cse516).
coursecode(ra,cse523).
coursecode(tmc,cse524).
coursecode(ga,cse525).
coursecode(ibc,cse528).
coursecode(aag,cse529).
coursecode(dscd,cse530).
coursecode(mas,cse531).
coursecode(mc,cse535).
coursecode(wn,cse538).
coursecode(ac,cse546).
coursecode(se,cse552).
coursecode(isc,cse555).
coursecode(nlp,cse556).
coursecode(bda,cse557).
coursecode(dsc,cse558).
coursecode(mln,cse559).
coursecode(gpu,cse560).
coursecode(pgm,cse561).
coursecode(acv,cse562).
coursecode(mca,cse563).
coursecode(rl,cse564).
coursecode(sdn,cse565).
coursecode(mms,cse566).
coursecode(vr,cse570).
coursecode(imc,cse571).
coursecode(sap,cse572).
coursecode(ssiot,cse576).
coursecode(aiot,cse577).
coursecode(om,cse580a).
coursecode(sadre,cse581).
coursecode(spem,cse582).
coursecode(sdos,cse583).
coursecode(pv,cse584).
coursecode(gp,cse5gp).
coursecode(oopd,cse600a).
coursecode(kg,cse605a).
coursecode(dw,cse606).
coursecode(dlm,cse606a).
coursecode(scomp,cse609).
coursecode(iqc,cse622).
coursecode(aos,cse631).
coursecode(sweb,cse632).
coursecode(irob,cse633).
coursecode(sr,cse633a).
coursecode(prmp,cse634).
coursecode(comn,cse636).
coursecode(cf,cse640).
coursecode(dl,cse641).
coursecode(aml,cse642).
coursecode(ai,cse643).
coursecode(psosm,cse645).
coursecode(tac,cse651).
coursecode(ns,cse655).
coursecode(iia,cse656).
coursecode(tais,cse660).
coursecode(afc,cse661).
coursecode(scv,cse662a).
coursecode(eai,cse663).
coursecode(mel,cse663a).
coursecode(ms,cse694f).
coursecode(tse,cse701).
coursecode(atmc,cse734).
coursecode(nap,cse749).
coursecode(tc,cse793a).
coursecode(ddv,des101).
coursecode(ihci,des102).
coursecode(pis,des130).
coursecode(dpp,des201).
coursecode(vdc,des202).
coursecode(hci,des204).
coursecode(iag,des302).
coursecode(fmrp,des303).
coursecode(fae,des501).
coursecode(i2d,des502).
coursecode(i3da,des503).
coursecode(nvc,des504).
coursecode(athcc,des506).
coursecode(fve,des507).
coursecode(df,des509).
coursecode(gdd,des512).
coursecode(wardi,des513).
coursecode(davp,des514).
coursecode(ispr,des515).
coursecode(i3dd,des516).
coursecode(i3d,des516s).
coursecode(img,des518).
coursecode(dis,des519).
coursecode(hcai,des520).
coursecode(iduda,des522).

coursecode(atd,ece631).
coursecode(rs,ece632).
coursecode(ssp,ece552).
coursecode(prp,ece501).
coursecode(dhd,ece510).
coursecode(vdf,ece513).
coursecode(scdt,ece516).
coursecode(ine,ece517).
coursecode(iai,ece519).
coursecode(lvacd,ece520).
coursecode(icf,ece522).
coursecode(qmd,ece524).
coursecode(snsf,ece533).
coursecode(ocs,ece534).
coursecode(on,ece536s).
coursecode(wce,ece537).
coursecode(wsi,ece539).
coursecode(pdcs,ece543).
coursecode(pho,ece545).
coursecode(owc,ece546).
coursecode(cs,ece554).
coursecode(sru,ece557).
coursecode(tla,ece558).
coursecode(gn,ece55g).
coursecode(dpm,ece560).
coursecode(lst,ece570).
coursecode(ocns,ece571).
coursecode(aeld,ece573).
coursecode(mlrc,ece577).
coursecode(nlr,ece579).
coursecode(ad,ece581).
coursecode(mdt,ece611).
coursecode(msd,ece612).
coursecode(sec,ece672).
coursecode(ma,eco201).
coursecode(eco,eco221).
coursecode(mb,eco223).
coursecode(me,eco301).
coursecode(iea,eco301).
coursecode(gmt,eco511).
coursecode(io,eco512).
coursecode(md,eco313).
coursecode(beco,eco314).
coursecode(econ-2,eco522).
coursecode(ssse,eco524).
coursecode(ff,eco331).
coursecode(vpm,eco332).
coursecode(drm,eco333).
coursecode(mdp,eco541).
coursecode(dt,eco503).
coursecode(rm,eng599s).
coursecode(ecomm,ent411).
coursecode(ek,ent412).
coursecode(ef,ent413).
coursecode(rips,ent414).
coursecode(nvp,ent415).
coursecode(ciips,ent516).
coursecode(hiee,ent421).
coursecode(evs,esc205).
coursecode(eee,esc207a).
coursecode(escm,mgt310).
coursecode(eiitm,mgt311).
coursecode(m-i,mth100).
coursecode(ps,mth201).
coursecode(m-iii,mth203).
coursecode(m-iv,mth204).
coursecode(ds,mth210).
coursecode(nt,mth211).
coursecode(aa-i,mth212).
coursecode(ra-i,mth240).
coursecode(nm,mth270).
coursecode(iml,mth300).
coursecode(alg,mth302).
coursecode(gt,mth310).
coursecode(cia,mth311).
coursecode(ra-ii,mth340).
coursecode(cmpa,mth541).
coursecode(ids,mth543).
coursecode(spa,mth371).
coursecode(si,mth372).
coursecode(sc,mth373).
coursecode(lo,mth574).
coursecode(fm,mth575).
coursecode(ala,mth510).
coursecode(ant,mth512).
coursecode(aa-ii,mth513).
coursecode(cot,mth514).
coursecode(annt,mth516).
coursecode(cmo,mth517).
coursecode(tnt,mth518).
coursecode(mpt,mth535).
coursecode(ifa,mth542).
coursecode(crn,mth544).
coursecode(fsem,mth545).
coursecode(ipde,mth550).
coursecode(pst,mth562).
coursecode(pst-2,mth562a).
coursecode(irg,mth564a).
coursecode(nsde,mth570).
coursecode(ita,mth571).
coursecode(cda,mth576).
coursecode(coo,mth577).
coursecode(npde,mth598).
coursecode(vca,mth599).
coursecode(psy,psy201).
coursecode(ppsy,psy202).
coursecode(cp,psy301).
coursecode(sp,psy302).
coursecode(atp,psy305).
coursecode(lm,psy306).
coursecode(ndm,psy307).
coursecode(cmm,psy308).
coursecode(isa,soc101).
coursecode(cisp,soc202).
coursecode(snm,soc204).
coursecode(asm,soc205).
coursecode(ba,soc206).
coursecode(its,soc207).
coursecode(oap,soc208).
coursecode(ccs,soc209).
coursecode(st1,soc210).
coursecode(sts,soc211).
coursecode(kces,soc212).
coursecode(ide,soc213).
coursecode(us,soc302).
coursecode(dsr,soc307).
coursecode(gm,soc308).
coursecode(aerm,soc501).
coursecode(ast,soc502).
coursecode(soi,soc503).
coursecode(tfm,soc512).
coursecode(inst,soc511).
coursecode(ctrss,ssh101).
coursecode(iphi,ssh121).
coursecode(ct,ssh124).
coursecode(rmssd,ssh201).
coursecode(ta,ssh211).
coursecode(lit,ssh214).
coursecode(nn,ssh215).
coursecode(iim,ssh216).
coursecode(ipa,ssh217).
coursecode(spp,ssh221).
coursecode(tpee,ssh222).
coursecode(pok,ssh223).
coursecode(cies,ssh224).
coursecode(dipp,ssh261).
coursecode(te,ssh300).
coursecode(aw,ssh311).
coursecode(ae,ssh321).
coursecode(nmp,ssh323).
coursecode(pom,ssh324).
coursecode(cpde,ssh361).
coursecode(uspp,ssh562).
coursecode(pt,ssh3pt).


codetobranch(bio506,bio).
codetobranch(bio511,bio).
codetobranch(bio512,bio).
codetobranch(bio522,bio).
codetobranch(bio523,bio).
codetobranch(bio524,bio).
codetobranch(bio531,bio).
codetobranch(bio532,bio).
codetobranch(bio533,bio).
codetobranch(bio534,bio).
codetobranch(bio541,bio).
codetobranch(bio542,bio).
codetobranch(bio543,bio).
codetobranch(bio544,bio).
codetobranch(bio545,bio).
codetobranch(bio546,bio).
codetobranch(bio561,bio).
codetobranch(com101,bio).
codetobranch(com301a,bio).
codetobranch(cse585,cse).
codetobranch(cse601,cse).
codetobranch(cse519,cse).
codetobranch(cse520,cse).
codetobranch(cse322,cse).
codetobranch(cse533,cse).
codetobranch(cse540,cse).
codetobranch(cse542,cse).
codetobranch(cse543,cse).
codetobranch(cse544,cse).
codetobranch(cse545,cse).
codetobranch(cse550,cse).
codetobranch(cse554,cse).
codetobranch(cse621,cse).
codetobranch(cse541,cse).
codetobranch(cse501,cse).
codetobranch(cse502,cse).
codetobranch(cse503,cse).
codetobranch(cse504,cse).
codetobranch(cse506,cse).
codetobranch(cse507,cse).
codetobranch(cse508,cse).
codetobranch(cse511,cse).
codetobranch(cse515,cse).
codetobranch(cse516,cse).
codetobranch(cse523,cse).
codetobranch(cse524,cse).
codetobranch(cse525,cse).
codetobranch(cse528,cse).
codetobranch(cse529,cse).
codetobranch(cse530,cse).
codetobranch(cse531,cse).
codetobranch(cse535,cse).
codetobranch(cse538,cse).
codetobranch(cse543,cse).
codetobranch(cse546,cse).
codetobranch(cse552,cse).
codetobranch(cse555,cse).
codetobranch(cse556,cse).
codetobranch(cse557,cse).
codetobranch(cse558,cse).
codetobranch(cse559,cse).
codetobranch(cse560,cse).
codetobranch(cse561,cse).
codetobranch(cse562,cse).
codetobranch(cse563,cse).
codetobranch(cse564,cse).
codetobranch(cse565,cse).
codetobranch(cse566,cse).
codetobranch(cse570,cse).
codetobranch(cse571,cse).
codetobranch(cse572,cse).
codetobranch(cse576,cse).
codetobranch(cse577,cse).
codetobranch(cse580a,cse).
codetobranch(cse581,cse).
codetobranch(cse582,cse).
codetobranch(cse583,cse).
codetobranch(cse584,cse).
codetobranch(cse5gp,cse).
codetobranch(cse600a,cse).
codetobranch(cse605a,cse).
codetobranch(cse606,cse).
codetobranch(cse606a,cse).
codetobranch(cse609,cse).
codetobranch(cse622,cse).
codetobranch(cse631,cse).
codetobranch(cse632,cse).
codetobranch(cse633,cse).
codetobranch(cse633a,cse).
codetobranch(cse634,cse).
codetobranch(cse636,cse).
codetobranch(cse640,cse).
codetobranch(cse641,cse).
codetobranch(cse642,cse).
codetobranch(cse643,cse).
codetobranch(cse645,cse).
codetobranch(cse651,cse).
codetobranch(cse655,cse).
codetobranch(cse656,cse).
codetobranch(cse660,cse).
codetobranch(cse661,cse).
codetobranch(cse662a,cse).
codetobranch(cse663,cse).
codetobranch(cse663a,cse).
codetobranch(cse694f,cse).
codetobranch(cse701,cse).
codetobranch(cse734,cse).
codetobranch(cse749,cse).
codetobranch(cse793a,cse).
codetobranch(des101,des).
codetobranch(des102,des).
codetobranch(des130,des).
codetobranch(des201,des).
codetobranch(des202,des).
codetobranch(des204,des).
codetobranch(des302,des).
codetobranch(des303,des).
codetobranch(des501,des).
codetobranch(des502,des).
codetobranch(des503,des).
codetobranch(des504,des).
codetobranch(des506,des).
codetobranch(des507,des).
codetobranch(des509,des).
codetobranch(des512,des).
codetobranch(des513,des).
codetobranch(des514,des).
codetobranch(des515,des).
codetobranch(des516,des).
codetobranch(des516s,des).
codetobranch(des518,des).
codetobranch(des519,des).
codetobranch(des520,des).
codetobranch(des522,des).
codetobranch(ece514,ece).
codetobranch(ece515,ece).
codetobranch(ece318,ece).
codetobranch(ece521,ece).
codetobranch(ece340,ece).
codetobranch(ece343,ece).
codetobranch(ece351,ece).
codetobranch(ece631,ece).
codetobranch(ece632,ece).
codetobranch(ece552,ece).
codetobranch(ece501,ece).
codetobranch(ece510,ece).
codetobranch(ece513,ece).
codetobranch(ece516,ece).
codetobranch(ece517,ece).
codetobranch(ece519,ece).
codetobranch(ece520,ece).
codetobranch(ece522,ece).
codetobranch(ece524,ece).
codetobranch(ece532,ece).
codetobranch(ece533,ece).
codetobranch(ece534,ece).
codetobranch(ece536s,ece).
codetobranch(ece537,ece).
codetobranch(ece539,ece).
codetobranch(ece543,ece).
codetobranch(ece545,ece).
codetobranch(ece546,ece).
codetobranch(ece554,ece).
codetobranch(ece557,ece).
codetobranch(ece558,ece).
codetobranch(ece55g,ece).
codetobranch(ece560,ece).
codetobranch(ece570,ece).
codetobranch(ece571,ece).
codetobranch(ece573,ece).
codetobranch(ece577,ece).
codetobranch(ece579,ece).
codetobranch(ece581,ece).
codetobranch(ece611,ece).
codetobranch(ece612,ece).
codetobranch(ece672,ece).
codetobranch(eco201,eco).
codetobranch(eco221,eco).
codetobranch(eco223,eco).
codetobranch(eco301,eco).
codetobranch(eco301,eco).
codetobranch(eco511,eco).
codetobranch(eco512,eco).
codetobranch(eco313,eco).
codetobranch(eco314,eco).
codetobranch(eco522,eco).
codetobranch(eco524,eco).
codetobranch(eco331,eco).
codetobranch(eco332,eco).
codetobranch(eco333,eco).
codetobranch(eco541,eco).
codetobranch(eco503,eco).
codetobranch(eng599s,eco).
codetobranch(ent411,eco).
codetobranch(ent412,eco).
codetobranch(ent413,eco).
codetobranch(ent414,eco).
codetobranch(ent415,eco).
codetobranch(ent516,eco).
codetobranch(ent421,eco).
codetobranch(esc205,eco).
codetobranch(esc207a,eco).
codetobranch(mgt310,eco).
codetobranch(mgt311,eco).
codetobranch(mth100,mth).
codetobranch(mth201,mth).
codetobranch(mth203,mth).
codetobranch(mth204,mth).
codetobranch(mth210,mth).
codetobranch(mth211,mth).
codetobranch(mth212,mth).
codetobranch(mth240,mth).
codetobranch(mth270,mth).
codetobranch(mth300,mth).
codetobranch(mth302,mth).
codetobranch(mth310,mth).
codetobranch(mth311,mth).
codetobranch(mth340,mth).
codetobranch(mth541,mth).
codetobranch(mth543,mth).
codetobranch(mth371,mth).
codetobranch(mth372,mth).
codetobranch(mth373,mth).
codetobranch(mth574,mth).
codetobranch(mth575,mth).
codetobranch(mth510,mth).
codetobranch(mth512,mth).
codetobranch(mth513,mth).
codetobranch(mth514,mth).
codetobranch(mth516,mth).
codetobranch(mth517,mth).
codetobranch(mth518,mth).
codetobranch(mth535,mth).
codetobranch(mth542,mth).
codetobranch(mth544,mth).
codetobranch(mth545,mth).
codetobranch(mth550,mth).
codetobranch(mth562,mth).
codetobranch(mth562a,mth).
codetobranch(mth564a,mth).
codetobranch(mth570,mth).
codetobranch(mth571,mth).
codetobranch(mth576,mth).
codetobranch(mth577,mth).
codetobranch(mth598,mth).
codetobranch(mth599,mth).
codetobranch(psy201,psy).
codetobranch(psy202,psy).
codetobranch(psy301,psy).
codetobranch(psy302,psy).
codetobranch(psy305,psy).
codetobranch(psy306,psy).
codetobranch(psy307,psy).
codetobranch(psy308,psy).
codetobranch(soc101,soc).
codetobranch(soc202,soc).
codetobranch(soc204,soc).
codetobranch(soc205,soc).
codetobranch(soc206,soc).
codetobranch(soc207,soc).
codetobranch(soc208,soc).
codetobranch(soc209,soc).
codetobranch(soc210,soc).
codetobranch(soc211,soc).
codetobranch(soc212,soc).
codetobranch(soc213,soc).
codetobranch(soc302,soc).
codetobranch(soc307,soc).
codetobranch(soc308,soc).
codetobranch(soc501,soc).
codetobranch(soc502,soc).
codetobranch(soc503,soc).
codetobranch(soc512,soc).
codetobranch(soc511,soc).
codetobranch(ssh101,ssh).
codetobranch(ssh121,ssh).
codetobranch(ssh124,ssh).
codetobranch(ssh201,ssh).
codetobranch(ssh211,ssh).
codetobranch(ssh214,ssh).
codetobranch(ssh215,ssh).
codetobranch(ssh216,ssh).
codetobranch(ssh217,ssh).
codetobranch(ssh221,ssh).
codetobranch(ssh222,ssh).
codetobranch(ssh223,ssh).
codetobranch(ssh224,ssh).
codetobranch(ssh261,ssh).
codetobranch(ssh300,ssh).
codetobranch(ssh311,ssh).
codetobranch(ssh321,ssh).
codetobranch(ssh323,ssh).
codetobranch(ssh324,ssh).
codetobranch(ssh361,ssh).
codetobranch(ssh562,ssh).
codetobranch(ssh3pt,ssh).



semester(sssbb,monsoon).
semester(cbb,monsoon).
semester(fomb,monsoon).
semester(acb,monsoon).
semester(chi,winter).
semester(bip,monsoon).
semester(imb,winter).
semester(nb,monsoon).
semester(ssb,winter).
semester(icn,winter).
semester(dsg,winter).
semester(mlba,monsoon).
semester(bdmh,winter).
semester(cgas,monsoon).
semester(biostats,winter).
semester(cm,monsoon).
semester(cadd,winter).
semester(com,monsoon).
semester(tcom,monsoon).
semester(cmp,monsoon).
semester(mad,monsoon).
semester(aa,monsoon).
semester(toc,winter).
semester(cg,monsoon).
semester(dip,monsoon).
semester(sml,winter).
semester(ml,monsoon).
semester(cv,winter).
semester(fcs,monsoon).
semester(nsc,monsoon).
semester(nss-ii,winter).
semester(cmpt,monsoon).
semester(biom,winter).
semester(dhcs,monsoon).
semester(fpp,winter).
semester(pa,monsoon).
semester(dp,winter).
semester(dmg,monsoon).
semester(dbsi,monsoon).
semester(ir,winter).
semester(ca,monsoon).
semester(bml,monsoon).
semester(tdl,winter).
semester(ra,monsoon).
semester(tmc,monsoon).
semester(ga,monsoon).
semester(ibc,winter).
semester(aag,winter).
semester(dscd,monsoon).
semester(mas,monsoon).
semester(mc,monsoon).
semester(wn,winter).
semester(ac,monsoon).
semester(se,monsoon).
semester(isc,monsoon).
semester(nlp,monsoon).
semester(bda,winter).
semester(dsc,monsoon).
semester(mln,winter).
semester(gpu,winter).
semester(pgm,winter).
semester(acv,monsoon).
semester(mca,winter).
semester(rl,monsoon).
semester(sdn,monsoon).
semester(mms,monsoon).
semester(vr,winter).
semester(imc,monsoon).
semester(sap,monsoon).
semester(ssiot,monsoon).
semester(aiot,winter).
semester(om,monsoon).
semester(sadre,winter).
semester(spem,monsoon).
semester(sdos,monsoon).
semester(pv,monsoon).
semester(gp,monsoon).
semester(oopd,monsoon).
semester(kg,monsoon).
semester(dw,winter).
semester(dlm,monsoon).
semester(scomp,winter).
semester(iqc,winter).
semester(aos,winter).
semester(sweb,winter).
semester(irob,winter).
semester(sr,winter).
semester(prmp,monsoon).
semester(comn,winter).
semester(cf,monsoon).
semester(dl,winter).
semester(aml,monsoon).
semester(ai,monsoon).
semester(psosm,winter).
semester(tac,monsoon).
semester(ns,winter).
semester(iia,monsoon).
semester(tais,winter).
semester(afc,monsoon).
semester(scv,winter).
semester(eai,winter).
semester(mel,winter).
semester(ms,winter).
semester(tse,monsoon).
semester(atmc,winter).
semester(nap,monsoon).
semester(tc,winter).
semester(ddv,winter).
semester(ihci,winter).
semester(pis,monsoon).
semester(dpp,monsoon).
semester(vdc,monsoon).
semester(hci,winter).
semester(iag,monsoon).
semester(fmrp,monsoon).
semester(fae,monsoon).
semester(i2d,winter).
semester(i3da,winter).
semester(nvc,winter).
semester(athcc,winter).
semester(fve,winter).
semester(df,monsoon).
semester(gdd,winter).
semester(wardi,monsoon).
semester(davp,monsoon).
semester(ispr,monsoon).
semester(i3dd,monsoon).
semester(i3d,winter).
semester(img,monsoon).
semester(dis,monsoon).
semester(hcai,monsoon).
semester(iduda,monsoon).
semester(atd,monsoon).
semester(rs,winter).
semester(ssp,winter).
semester(prp,monsoon).
semester(dhd,monsoon).
semester(vdf,monsoon).
semester(scdt,monsoon).
semester(ine,winter).
semester(iai,monsoon).
semester(lvacd,monsoon).
semester(icf,monsoon).
semester(qmd,monsoon).
semester(ofni,monsoon).
semester(snsf,monsoon).
semester(ocs,winter).
semester(wce,winter).
semester(wsi,winter).
semester(pdcs,monsoon).
semester(pho,monsoon).
semester(owc,monsoon).
semester(cs,monsoon).
semester(sru,winter).
semester(tla,winter).
semester(dpm,monsoon).
semester(lst,monsoon).
semester(ocns,winter).
semester(aeld,winter).
semester(mlrc,winter).
semester(nlr,monsoon).
semester(ad,winter).
semester(mdt,winter).
semester(msd,winter).
semester(sec,winter).
semester(ma,monsoon).
semester(eco,monsoon).
semester(mb,winter).
semester(me,winter).
semester(iea,monsoon).
semester(gmt,monsoon).
semester(io,winter).
semester(md,winter).
semester(beco,monsoon).
semester(econ-2,monsoon).
semester(ssse,winter).
semester(ff,monsoon).
semester(vpm,winter).
semester(drm,monsoon).
semester(mdp,monsoon).
semester(dt,monsoon).
semester(rm,winter).
semester(ecomm,monsoon).
semester(ek,monsoon).
semester(ef,winter).
semester(rips,winter).
semester(nvp,winter).
semester(ciips,winter).
semester(hiee,monsoon).
semester(vevs,monsoon).
semester(eee,monsoon).
semester(escm,monsoon).
semester(eiitm,winter).
semester(m-i,monsoon).
semester(m-iii,monsoon).
semester(m-iv,winter).
semester(ds,monsoon).
semester(nt,monsoon).
semester(aa-i,winter).
semester(ra-i,monsoon).
semester(nm,monsoon).
semester(iml,winter).
semester(alg,monsoon).
semester(gt,winter).
semester(cia,winter).
semester(ra-ii,monsoon).
semester(cmpa,monsoon).
semester(ids,winter).
semester(spa,monsoon).
semester(si,winter).
semester(sc,monsoon).
semester(lo,winter).
semester(fm,monsoon).
semester(ala,winter).
semester(ant,monsoon).
semester(aa-ii,winter).
semester(cot,winter).
semester(annt,winter).
semester(cmo,winter).
semester(tnt,monsoon).
semester(mpt,winter).
semester(ifa,winter).
semester(crn,winter).
semester(fsem,monsoon).
semester(ipde,winter).
semester(pst,monsoon).
semester(pst-2,monsoon).
semester(irg,monsoon).
semester(nsde,winter).
semester(ita,winter).
semester(cda,monsoon).
semester(coo,winter).
semester(npde,winter).
semester(vca,winter).
semester(psy,monsoon).
semester(ppsy,winter).
semester(cp,winter).
semester(sp,winter).
semester(atp,winter).
semester(lm,winter).
semester(ndm,monsoon).
semester(cmm,monsoon).
semester(isa,winter).
semester(cisp,monsoon).
semester(snm,monsoon).
semester(asm,winter).
semester(ba,monsoon).
semester(its,winter).
semester(oap,winter).
semester(ccs,monsoon).
semester(st1,winter).
semester(sts,winter).
semester(kces,monsoon).
semester(ide,winter).
semester(us,winter).
semester(dsr,monsoon).
semester(gm,monsoon).
semester(aerm,monsoon).
semester(ast,winter).
semester(soi,winter).
semester(tfm,monsoon).
semester(inst,monsoon).
semester(ctrss,winter).
semester(iphi,monsoon).
semester(ct,winter).
semester(rmssd,monsoon).
semester(ta,monsoon).
semester(lit,winter).
semester(nn,winter).
semester(iim,monsoon).
semester(ipa,winter).
semester(spp,monsoon).
semester(tpee,winter).
semester(pok,monsoon).
semester(cies,winter).
semester(dipp,winter).
semester(te,monsoon).
semester(aw,winter).
semester(ae,winter).
semester(nmp,monsoon).
semester(pom,winter).
semester(cpde,winter).
semester(uspp,monsoon).
semester(pt,winter).

prerequisites(bio531,sssbb).
prerequisites(none,cbb).
prerequisites(none,fomb).
prerequisites(none,acb).
prerequisites(none,chi).
prerequisites(none,bip).
prerequisites(none,imb).
prerequisites(none,nb).
prerequisites(bio531,ssb).
prerequisites(none,icn).
prerequisites(none,dsg).
prerequisites(none,mlba).
prerequisites(none,bdmh).
prerequisites(none,cgas).
prerequisites(none,biostats).
prerequisites(none,cm).
prerequisites(none,cadd).
prerequisites(none,com).
prerequisites(none,tcom).
prerequisites(none,cmp).
prerequisites(none,mad).
prerequisites(none,aa).
prerequisites(none,toc).
prerequisites(none,cg).
prerequisites(none,dip).
prerequisites(none,sml).
prerequisites(none,ml).
prerequisites(none,cv).
prerequisites(none,fcs).
prerequisites(none,nsc).
prerequisites(none,nss-ii).
prerequisites(none,cmpt).
prerequisites(cse543,biom).
prerequisites(none,dhcs).
prerequisites(none,fpp).
prerequisites(none,pa).
prerequisites(none,dp).
prerequisites(none,dmg).
prerequisites(none,dbsi).
prerequisites(none,ir).
prerequisites(none,ca).
prerequisites(none,bml).
prerequisites(cse542,tdl).
prerequisites(none,ra).
prerequisites(none,tmc).
prerequisites(none,ga).
prerequisites(cse546,ibc).
prerequisites(none,aag).
prerequisites(none,dscd).
prerequisites(none,mas).
prerequisites(none,mc).
prerequisites(none,wn).
prerequisites(none,ac).
prerequisites(none,se).
prerequisites(none,isc).
prerequisites(none,nlp).
prerequisites(none,bda).
prerequisites(none,dsc).
prerequisites(none,mln).
prerequisites(none,gpu).
prerequisites(none,pgm).
prerequisites(cse544,acv).
prerequisites(none,mca).
prerequisites(none,rl).
prerequisites(none,sdn).
prerequisites(cse535,mms).
prerequisites(none,vr).
prerequisites(none,imc).
prerequisites(none,sap).
prerequisites(none,ssiot).
prerequisites(none,aiot).
prerequisites(none,om).
prerequisites(none,sadre).
prerequisites(none,spem).
prerequisites(none,sdos).
prerequisites(none,pv).
prerequisites(none,gp).
prerequisites(none,oopd).
prerequisites(cse551,kg).
prerequisites(none,dw).
prerequisites(cse543,dlm).
prerequisites(none,scomp).
prerequisites(none,iqc).
prerequisites(none,aos).
prerequisites(none,sweb).
prerequisites(none,irob).
prerequisites(none,sr).
prerequisites(none,prmp).
prerequisites(none,comn).
prerequisites(none,cf).
prerequisites(none,dl).
prerequisites(cse542,aml).
prerequisites(none,ai).
prerequisites(none,psosm).
prerequisites(cse545,tac).
prerequisites(none,ns).
prerequisites(none,iia).
prerequisites(cse542,tais).
prerequisites(none,afc).
prerequisites(none,scv).
prerequisites(cse543,eai).
prerequisites(cse643,mel).
prerequisites(none,ms).

prerequisites(none,atmc).
prerequisites(none,nap).
prerequisites(none,tc).
prerequisites(none,ddv).
prerequisites(none,ihci).
prerequisites(none,pis).
prerequisites(none,vdc).
prerequisites(none,hci).
prerequisites(none,iag).
prerequisites(none,fmrp).
prerequisites(none,fae).
prerequisites(des518,i2d).
prerequisites(des516,i3da).
prerequisites(none,nvc).
prerequisites(none,athcc).
prerequisites(none,fve).
prerequisites(des519,df).
prerequisites(none,gdd).
prerequisites(none,wardi).
prerequisites(none,davp).
prerequisites(none,ispr).
prerequisites(none,i3dd).
prerequisites(none,i3d).
prerequisites(none,img).
prerequisites(none,dis).
prerequisites(cse643,hcai).
prerequisites(dpp,iduda).
prerequisites(none,atd).
prerequisites(none,rs).
prerequisites(none,ssp).
prerequisites(none,prp).
prerequisites(none,dhd).
prerequisites(none,vdf).
prerequisites(none,scdt).
prerequisites(none,ine).
prerequisites(none,iai).
prerequisites(ece515,lvacd).
prerequisites(none,icf).
prerequisites(none,ofni).
prerequisites(none,snsf).
prerequisites(none,ocs).
prerequisites(none,on).
prerequisites(none,wce).
prerequisites(none,wsi).
prerequisites(none,pdcs).
prerequisites(none,pho).
prerequisites(none,owc).
prerequisites(none,cs).
prerequisites(none,sru).
prerequisites(none,tla).
prerequisites(none,gn).
prerequisites(none,dpm).
prerequisites(none,lst).
prerequisites(none,ocns).
prerequisites(none,aeld).
prerequisites(none,mlrc).
prerequisites(none,nlr).
prerequisites(none,ad).
prerequisites(none,mdt).
prerequisites(ece515,msd).
prerequisites(ece501,sec).
prerequisites(none,ma).
prerequisites(none,eco).
prerequisites(none,mb).
prerequisites(none,me).
prerequisites(none,iea).
prerequisites(none,gmt).
prerequisites(none,io).
prerequisites(none,md).
prerequisites(none,beco).
prerequisites(none,econ-2).
prerequisites(none,ssse).
prerequisites(none,ff).
prerequisites(none,vpm).
prerequisites(none,drm).
prerequisites(none,mdp).
prerequisites(none,dt).
prerequisites(none,rm).
prerequisites(none,ecomm).
prerequisites(none,ek).
prerequisites(none,ef).
prerequisites(none,rips).
prerequisites(none,nvp).
prerequisites(none,ciips).
prerequisites(none,hiee).
prerequisites(none,evs).
prerequisites(none,eee).
prerequisites(none,escm).
prerequisites(none,eiitm).
prerequisites(none,m-i).
prerequisites(none,ps).
prerequisites(none,m-iii).
prerequisites(none,m-iv).
prerequisites(none,ds).
prerequisites(none,nt).
prerequisites(none,aa-i).
prerequisites(none,ra-i).
prerequisites(none,nm).
prerequisites(none,iml).
prerequisites(none,alg).
prerequisites(none,gt).
prerequisites(none,cia).
prerequisites(none,ra-ii).
prerequisites(none,cmpa).
prerequisites(none,ids).
prerequisites(none,spa).
prerequisites(none,si).
prerequisites(none,sc).
prerequisites(none,lo).
prerequisites(none,fm).
prerequisites(none,ala).
prerequisites(none,ant).
prerequisites(none,aa-ii).
prerequisites(mth513,cot).
prerequisites(none,annt).
prerequisites(mth574,cmo).
prerequisites(none,tnt).
prerequisites(none,mpt).
prerequisites(none,ifa).
prerequisites(none,crn).
prerequisites(none,pst).
prerequisites(none,pst-2).
prerequisites(none,irg).
prerequisites(none,nsde).
prerequisites(none,ita).
prerequisites(none,cda).
prerequisites(none,coo).
prerequisites(none,npde).
prerequisites(none,vca).
prerequisites(none,psy).
prerequisites(none,ppsy).
prerequisites(none,cp).
prerequisites(none,sp).
prerequisites(none,atp).
prerequisites(none,lm).
prerequisites(none,ndm).
prerequisites(none,cmm).
prerequisites(none,isa).
prerequisites(none,cisp).
prerequisites(none,snm).
prerequisites(none,asm).
prerequisites(none,ba).
prerequisites(none,its).
prerequisites(none,oap).
prerequisites(none,ccs).
prerequisites(none,st1).
prerequisites(none,sts).
prerequisites(none,kces).
prerequisites(none,ide).
prerequisites(none,us).
prerequisites(none,dsr).
prerequisites(none,gm).
prerequisites(none,aerm).
prerequisites(none,ast).
prerequisites(none,soi).
prerequisites(none,tfm).
prerequisites(none,inst).
prerequisites(none,ctrss).
prerequisites(none,iphi).
prerequisites(none,ct).
prerequisites(none,rmssd).
prerequisites(none,ta).
prerequisites(none,lit).
prerequisites(none,nn).
prerequisites(none,iim).
prerequisites(none,ipa).
prerequisites(none,spp).
prerequisites(none,tpee).
prerequisites(none,pok).
prerequisites(none,cies).
prerequisites(none,dipp).
prerequisites(none,te).
prerequisites(none,aw).
prerequisites(none,ae).
prerequisites(none,nmp).
prerequisites(ssh121,pom).
prerequisites(none,cpde).
prerequisites(none,uspp).
prerequisites(none,pt).


%%%%%%% rules

allprerequisites(A,B):- prerequisites(A,B);
                       prerequisites(A,C),allprerequisites(C,B).
start:-
    write("Welcome to course advisory system for M.Tech students"),nl,nl,
    write("Are you a new student who want to choose subjects for the first time - press y./n."),nl,nl,
    read(X),X==y -> newstudent;oldstudent.

newstudent:-
     %%(prerequisites(none,A),coursename(A,B),semester(A,monsoon)),
    %findall(B,(prerequisites(none,A),coursename(A,B),semester(A,monsoon)), C),
    %write(C),nl,nl,nl,
    write("Enter your interest to filter subjects specific to you in coming semester. Enter number."),nl,nl,nl,
    write("1.CSE,    2.ECE,    3.CB,    4.MATHS,    5.Psy,    6.Des.  7.Economics   8. ssh   9. soc"),nl,nl,
    read(Z),((Z==1 -> cse);(Z==1 -> cse);(Z==2 -> ece);(Z==3 -> cb);(Z==4 -> maths);(Z==5 -> psy);(Z==6 -> des);(Z==7 -> eco);(Z==8 -> ssh);(Z==9 -> soc)),write("These are the courses for monsoon semester with no prerequisites so can be taken in first semester."),nl,nl.

cse:-
    write("You opt cse.Out of the above, these are courses you an take with no prerequisites.  -"),nl,nl,
    findall(A,(codetobranch(C,cse),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.
eco:-
    write("You opt eco.Out of the above, these are courses you an take with no prerequisites.  -"),nl,nl,
    findall(A,(codetobranch(C,eco),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.

ssh:-
    write("You opt ssh.Out of the above, these are courses you an take with no prerequisites.  -"),nl,nl,
    findall(A,(codetobranch(C,ssh),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.

soc:-
    write("You opt soc.Out of the above, these are courses you an take with no prerequisites.  -"),nl,nl,
    findall(A,(codetobranch(C,soc),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.

ece:-
    write("You opt ece.  Out of them, these are courses available to you.  -"),nl,nl,
     findall(A,(codetobranch(C,ece),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.
cb:-
    write("You opt cb . Out of them, these are courses available to you.  -"),nl,nl,
     findall(A,(codetobranch(C,bio),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.
maths:-
    write("You opt maths .Out of them, these are courses available to you.  -"),nl,nl,
     findall(A,(codetobranch(C,mth),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.
psy:-
    write("You opt psy.Out of them, these are courses available to you.  -"),nl,nl,
     findall(A,(codetobranch(C,psy),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.
des:-
    write("You opt des.Out of them, these are courses available to you.  -"),nl,nl,
     findall(A,(codetobranch(C,des),coursecode(B,C),prerequisites(none,B),semester(B,monsoon),coursename(B,A)), Q),
    write(Q),nl,nl.


oldstudent:-
    write("Which semester is next - monsoon/winter."),nl,nl,
    read(Sem),
    write("Enter your interest from - "),nl, write("cse.    ece.    bio.   mth.     des.     eco.     psy.     soc.      ssh."),nl,nl,read(Branch),
     findall(A,(codetobranch(C,Branch),coursecode(B,C),prerequisites(none,B),semester(B,Sem),coursename(B,A)), Q),write("These are courses offered in the selected semester with no prerequisites for M.Tech, so can be taken by you."),nl,nl,write(Q),nl,nl,nl,


    write("Enter course code which you took in previous sems (end by dot) -"),nl,nl,
    read(Y),nl,nl,write("We now mention the courses for which the entered course is a prerequsite or none is the prerequsite and is offered in the selected semester."),nl,nl,coursecode(Y,L),
    findall(P,(codetobranch(C,Branch),coursecode(X,C),prerequisites(L,X),semester(X,Sem),coursename(X,P)), Z)->write(Z);
    (   findall(P,(codetobranch(C,Branch),coursecode(X,C),prerequisites(none,X),semester(X,Sem),coursename(X,P)), E),write(E)).

    %advicecourses.
   % write(Q),nl,nl.

test:-
    (prerequisites(none,A),semester(A,monsoon),coursename(A,B)),write(B).

plist([P|List]) :-
        write(P),nl,
        plist(List).





